# Generated by Django 5.1.1 on 2024-10-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_time_to_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время на выполнение"
            ),
        ),
    ]
