# Generated by Django 5.1.1 on 2024-10-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_yourcelerybeatmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YourCeleryBeatModel",
        ),
    ]
