[tool.poetry]
name = "14-2"
version = "0.1.0"
description = ""
authors = ["Elvina <Elle-elle7@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
