# Generated by Django 5.1 on 2024-08-09 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_alter_lesson_url_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="course_name",
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="learning.course",
                verbose_name="курс",
            ),
        ),
    ]
