# Generated by Django 5.1 on 2024-09-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Название курса"
            ),
        ),
    ]
