# Generated by Django 5.0.7 on 2024-07-22 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='client',
            field=models.ManyToManyField(to='main.client', verbose_name='Имена клиентов'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='сообщение для клиентов'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_name',
            field=models.CharField(max_length=150, verbose_name='Название рассылки'),
        ),
    ]
