# Generated by Django 5.0.7 on 2024-07-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки отправки'),
        ),
    ]
