# Generated by Django 5.0.7 on 2024-07-22 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_newsletter_client_alter_newsletter_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 23, 19, 15, 47, 458458, tzinfo=datetime.timezone.utc), null=True, verbose_name='дата и время первой отправки рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('запущена', 'запущена'), ('создана', 'создана'), ('завершена', 'завершена')], default='создана', max_length=100, verbose_name='статус рассылки'),
        ),
    ]
