# Generated by Django 5.0.7 on 2024-07-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(choices=[('month', 'раз в месяц'), ('day', 'раз в день'), ('week', 'раз в неделю'), ('minute', 'раз в минуту')], default='month', max_length=100, verbose_name='периодичность'),
        ),
    ]
