# Generated by Django 5.0.7 on 2024-07-23 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_newsletter_created_at_alter_newsletter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='created_at',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='date_end',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата окончания рассылки'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='date_next',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='следующая дата рассылки'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='date_start',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата начала рассылки'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='start_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Время рассылки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия'),
        ),
    ]
