# Generated by Django 4.2.2 on 2024-07-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_owner_message_owner_newsletter_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('newsletter_name',), 'permissions': [('deactivate_mailing', 'Can deactivate mailing'), ('view_all_mailings', 'Can view all mailings')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
