# Generated by Django 5.0.6 on 2024-09-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0008_car_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="amount",
            new_name="price",
        ),
        migrations.AddField(
            model_name="moto",
            name="price",
            field=models.IntegerField(default=1000, verbose_name="цена"),
        ),
    ]
