# Generated by Django 5.0.6 on 2024-07-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="current_version_indicator",
            field=models.BooleanField(
                default=False, verbose_name="признак текущей версии"
            ),
        ),
    ]
