# Generated by Django 5.1 on 2024-09-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(
                auto_created=True, blank=True, null=True, verbose_name="дата оплаты"
            ),
        ),
    ]
